# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VLSI/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/c_counter_binary/ip/c_counter_binary_div_xAxis_1/c_counter_binary_div_xAxis_1.xci
# IP: The module: 'c_counter_binary_div_xAxis_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VLSI/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/c_counter_binary/ip/c_counter_binary_div_xAxis_1/c_counter_binary_div_xAxis_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_div_xAxis_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/VLSI/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/c_counter_binary/ip/c_counter_binary_div_xAxis_1/c_counter_binary_div_xAxis_1.xci
# IP: The module: 'c_counter_binary_div_xAxis_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VLSI/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/c_counter_binary/ip/c_counter_binary_div_xAxis_1/c_counter_binary_div_xAxis_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_div_xAxis_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
