# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Zybo-Z7-Master.xdc

# Block Designs: bd/c_counter_binary/c_counter_binary.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary || ORIG_REF_NAME==c_counter_binary} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_detect_end_image_0_1/c_counter_binary_detect_end_image_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_detect_end_image_0_1 || ORIG_REF_NAME==c_counter_binary_detect_end_image_0_1} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_div_xAxis_1/c_counter_binary_div_xAxis_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_div_xAxis_1 || ORIG_REF_NAME==c_counter_binary_div_xAxis_1} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_div_yAxis_0/c_counter_binary_div_yAxis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_div_yAxis_0 || ORIG_REF_NAME==c_counter_binary_div_yAxis_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_divideur_select_outp_0_0/c_counter_binary_divideur_select_outp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_divideur_select_outp_0_0 || ORIG_REF_NAME==c_counter_binary_divideur_select_outp_0_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_divideur_select_outp_1_0/c_counter_binary_divideur_select_outp_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_divideur_select_outp_1_0 || ORIG_REF_NAME==c_counter_binary_divideur_select_outp_1_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_Counter_0_0/c_counter_binary_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_Counter_0_0 || ORIG_REF_NAME==c_counter_binary_Counter_0_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_ligne_counter_1/c_counter_binary_ligne_counter_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_ligne_counter_1 || ORIG_REF_NAME==c_counter_binary_ligne_counter_1} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_adapt_input_ouput_0_0/c_counter_binary_adapt_input_ouput_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_adapt_input_ouput_0_0 || ORIG_REF_NAME==c_counter_binary_adapt_input_ouput_0_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_adapt_input_ouput_0_1/c_counter_binary_adapt_input_ouput_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_adapt_input_ouput_0_1 || ORIG_REF_NAME==c_counter_binary_adapt_input_ouput_0_1} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_adapt_input_ouput_0_2/c_counter_binary_adapt_input_ouput_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_adapt_input_ouput_0_2 || ORIG_REF_NAME==c_counter_binary_adapt_input_ouput_0_2} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_ligne_counter_0/c_counter_binary_ligne_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_ligne_counter_0 || ORIG_REF_NAME==c_counter_binary_ligne_counter_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_adapt_input_ouput_1_0/c_counter_binary_adapt_input_ouput_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_adapt_input_ouput_1_0 || ORIG_REF_NAME==c_counter_binary_adapt_input_ouput_1_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_adapt_input_ouput_3_0/c_counter_binary_adapt_input_ouput_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_adapt_input_ouput_3_0 || ORIG_REF_NAME==c_counter_binary_adapt_input_ouput_3_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_Additionneur_Nbits_0_0/c_counter_binary_Additionneur_Nbits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_Additionneur_Nbits_0_0 || ORIG_REF_NAME==c_counter_binary_Additionneur_Nbits_0_0} -quiet] -quiet

# IP: bd/c_counter_binary/ip/c_counter_binary_Additionneur_Nbits_1_0/c_counter_binary_Additionneur_Nbits_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_Additionneur_Nbits_1_0 || ORIG_REF_NAME==c_counter_binary_Additionneur_Nbits_1_0} -quiet] -quiet

# XDC: bd/c_counter_binary/c_counter_binary_ooc.xdc
