# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/test/ip/test_div_gen_0_0/test_div_gen_0_0.xci
# IP: The module: 'test_div_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/test/ip/test_div_gen_0_0/test_div_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_div_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/test/ip/test_div_gen_0_0/test_div_gen_0_0.xci
# IP: The module: 'test_div_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/test/ip/test_div_gen_0_0/test_div_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_div_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
