# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/NMLEM1/Desktop/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/detection_centre/ip/detection_centre_BlankPixel_counter_0/detection_centre_BlankPixel_counter_0.xci
# IP: The module: 'detection_centre_BlankPixel_counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/NMLEM1/Desktop/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/detection_centre/ip/detection_centre_BlankPixel_counter_0/detection_centre_BlankPixel_counter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'detection_centre_BlankPixel_counter_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/NMLEM1/Desktop/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/detection_centre/ip/detection_centre_BlankPixel_counter_0/detection_centre_BlankPixel_counter_0.xci
# IP: The module: 'detection_centre_BlankPixel_counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/NMLEM1/Desktop/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/detection_centre/ip/detection_centre_BlankPixel_counter_0/detection_centre_BlankPixel_counter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'detection_centre_BlankPixel_counter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
