# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VLSI/Projet/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_Ligne_counter_0/HDMI_bd_Ligne_counter_0.xci
# IP: The module: 'HDMI_bd_Ligne_counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VLSI/Projet/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_Ligne_counter_0/HDMI_bd_Ligne_counter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_bd_Ligne_counter_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/VLSI/Projet/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_Ligne_counter_0/HDMI_bd_Ligne_counter_0.xci
# IP: The module: 'HDMI_bd_Ligne_counter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VLSI/Projet/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_Ligne_counter_0/HDMI_bd_Ligne_counter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_bd_Ligne_counter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
