# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_add_yAxis_1/HDMI_bd_add_yAxis_1.xci
# IP: The module: 'HDMI_bd_add_yAxis_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_add_yAxis_1/HDMI_bd_add_yAxis_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_bd_add_yAxis_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_add_yAxis_1/HDMI_bd_add_yAxis_1.xci
# IP: The module: 'HDMI_bd_add_yAxis_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nicol/Documents/GitHub/ProjetVision/VHDL/Segmentation+detectionCentre/ZYBO_HDMI_MGA/project_1/project_1.srcs/sources_1/bd/HDMI_bd/ip/HDMI_bd_add_yAxis_1/HDMI_bd_add_yAxis_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_bd_add_yAxis_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
